spring:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    
externalServices:
  coinPaprika:
    apiUrl: ${COIN_PAPRIKA_API_URL}
    
jwt:
  secret: ${JWT_SECRET}
  expiry: ${JWT_EXPIRY}