spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
    
externalServices:
  coinPaprika:
    apiUrl: https://api.coinpaprika.com/v1/
    
jwt:
  secret: 123456
  expiry: 999999999999