# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  kubernetes: circleci/kubernetes@1.3.1
  docker: circleci/docker@2.1.2

jobs:
  build:
    parameters:
      IMAGE_TAG:
        type: string
        default: ""
        
    docker:
      - image: cimg/openjdk:18.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    resource_class: medium

    working_directory: ~/mycryptolistapi
    
    steps:
      # git pull
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true    
      - when:
          condition:
            equal: [ main, master, << pipeline.git.branch >> ]
          steps:
            - run: llucasbrandao/mycryptolistapi:production:${CIRCLE_BUILD_NUM} >> << parameters.IMAGE_TAG >>
      - when:
          condition:
            not: 
              equal: [ main, master, << pipeline.git.branch >> ]
          steps:
            - run: llucasbrandao/mycryptolistapi:staging:${CIRCLE_BUILD_NUM} >> << parameters.IMAGE_TAG >>
      - run: echo << parameters.IMAGE_TAG >>

      - run: 
          name: Publish Docker Image to Docker Hub
          command: |
            docker build -t << parameters.IMAGE_TAG >> .
            echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
            docker push << parameters.IMAGE_TAG >>

  staging-cluster-deploy:
    description: Staging Cluster Deploy
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    resource_class: medium
      
    working_directory: ~/mycryptolistapi
    
    steps:
      - checkout

      - kubernetes/install-kubectl:
        kubectl-version: latest 

      - kubernetes/install-kubeconfig:
        kubeconfig: KUBECONFIG_DATA
        
      - kubernetes/create-or-update-resource:
          resource-name: deployment/mycrypto 
          show-kubectl-command: true 
          get-rollout-status: true 
          resource-file-path: .circleci/deployment.yaml 
          server-side-apply: true
          action-type: apply

  production-cluster-deploy:
    description: Production Cluster Deploy
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    resource_class: medium
      
    working_directory: ~/mycryptolistapi
    
    steps:
      - checkout
      
      - kubernetes/install-kubectl:
        kubectl-version: latest 

      - kubernetes/install-kubeconfig:
        kubeconfig: KUBECONFIG_DATA
      
      - kubernetes/create-or-update-resource:
          resource-name: deployment/mycrypto 
          show-kubectl-command: true 
          get-rollout-status: true 
          resource-file-path: .circleci/deployment.yaml 
          server-side-apply: true
          action-type: apply

workflows:
  version: 2
  mycryptolist-deployment-workflow:
    jobs:
      - build:
          name: Build & Publish Docker Image
      - deployment-approval:
          name: Waiting approval
          type: approval
          requires:
            - Build & Publish Docker Image
      - staging-cluster-deploy:
          name: Deploy to Staging Cluster
          filters:
            branches:
              ignore:
                - master
                - main
          requires:
            - Waiting approval
      - production-cluster-deploy:
          name: Deploy to Production Cluster
          filters:
            branches:
              only:
                - master
                - main
          requires:
            - Waiting approval