name: 'Container CI'

on:
  push:
    branches:
      - master
  
  pull_request: # [master, next]
    paths:
      - /

jobs:
  container:
    name: 'Build Container'
    runs-on: ubuntu-latest
    environment: 
      name: staging

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: /
        shell: bash

    steps:

    - if: github.event_name == 'push'
      name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3 
      with:
        token: ${{secrets.github_token}}    
   
    - name: Check Out Repo 
      if: github.event_name == 'push'
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      if: github.event_name == 'push'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    # Typical Java workflow steps
    - uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    # Step that does that actual cache save and restore
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    # Step that runs the tests
    #- name: Run tests
      #run: mvn test
  
  deployment: 
    runs-on: ubuntu-latest
    environment: 
      name: staging
      
    steps:
      - name: Set up Docker Buildx
        if: github.event_name == 'push'
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        if: github.event_name == 'push'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: /Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mycryptolistapi:latest #${{ steps.buildnumber.outputs.build_number }}
  
  
